EXPERIMENT_NAME: 'source_only_pretrain'
MODEL:
  DEVICE: 'cuda'
INPUT:
  NUM_WORKERS: 8
  NUM_POINTS: 2048
  ROT_DEGREE: 10.
  TRANSLATION: 0.1
SOLVER:
  USE_AMP: False
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00001
  NUM_EPOCHS: 15
  LR_MILESTONES: []
